force-app/main/default/objects/Employee_Training__c/Employee_Training__c.object-meta.xml
<CustomObject>
    <description>Custom object to relate employees with trainings</description>
    <label>Employee Training</label>
    <nameField>
        <label>Employee Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Training__c/fields/Achieved__c.field-meta.xml
<CustomField>
    <fullName>Achieved__c</fullName>
    <label>Achieved</label>
    <summarizedField>Employee_Activity__c.Total_Minutes__c</summarizedField>
    <summaryFilterItems>
        <field>Employee_Activity__c.Status__c</field>
        <operation>equals</operation>
        <value>Complete</value>
    </summaryFilterItems>
    <summaryForeignKey>Employee_Activity__c.Employee_Training__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Actual_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Actual_Minutes__c</fullName>
    <label>Actual Minutes</label>
    <summarizedField>Employee_Activity__c.Actual_Minutes__c</summarizedField>
    <summaryFilterItems>
        <field>Employee_Activity__c.Status__c</field>
        <operation>equals</operation>
        <value>Complete</value>
    </summaryFilterItems>
    <summaryForeignKey>Employee_Activity__c.Employee_Training__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Ahead_Behind__c.field-meta.xml
<CustomField>
    <fullName>Ahead_Behind__c</fullName>
    <formula>IF(
    (Days_in_Training__c * 60) - Total_Minutes__c&lt;0,
    &quot;(&quot;,
    &quot;&quot;
) 
&amp; 
IF(
    ABS((Days_in_Training__c * 60) - Total_Minutes__c)=0,
    &quot;0m&quot;,
    IF(
        ABS((Days_in_Training__c * 60) - Total_Minutes__c)&gt;=60,
        TEXT(FLOOR(ABS((Days_in_Training__c * 60) - Total_Minutes__c)/60)) &amp; &quot;h&quot;,
        &quot;&quot;
    ) 
    &amp; 
    IF(
        MOD(ABS((Days_in_Training__c * 60) - Total_Minutes__c),60)&gt;0,
        IF(
            ABS((Days_in_Training__c * 60) - Total_Minutes__c)&gt;=60,
            &quot; &quot;,
            &quot;&quot;
        ) 
        &amp; 
        TEXT(MOD(ABS((Days_in_Training__c * 60) - Total_Minutes__c),60)) &amp; &quot;m&quot;,
        &quot;&quot;
    )
) 
&amp; 
IF(
    (Days_in_Training__c * 60) - Total_Minutes__c&lt;0, 
    &quot;)&quot;,
    &quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ahead / Behind</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Days_in_Training__c.field-meta.xml
<CustomField>
    <fullName>Days_in_Training__c</fullName>
    <formula>IF(Start_Date__c &gt; TODAY(),0, TODAY()-Start_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days in Training</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF(
    Total_Minutes__c = 0,
    &quot;0m&quot;,
    IF(
        Total_Minutes__c &gt;= 60,
        TEXT(FLOOR(Total_Minutes__c/60)) &amp; &quot;h&quot;,
        &quot;&quot;
    ) &amp;
    IF(
        MOD(Total_Minutes__c,60) &gt; 0,
        IF(
            Total_Minutes__c &gt;= 60,
            &quot; &quot;,
            &quot;&quot;
        ) &amp;
        TEXT(MOD(Total_Minutes__c,60)) &amp; &quot;m&quot;,&quot;&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Start_Date__c + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>&quot;On Pace&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Target_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Target_Minutes__c</fullName>
    <formula>Days_in_Training__c * 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Total_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Total_Minutes__c</fullName>
    <description>Sum of total minutes from related employee activities</description>
    <label>Total Minutes</label>
    <summarizedField>Employee_Activity__c.Total_Minutes__c</summarizedField>
    <summaryForeignKey>Employee_Activity__c.Employee_Training__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/EmployeeTrainingController.cls
public with sharing class EmployeeTrainingController {

    @AuraEnabled
    public static List<Employee_Training__c> getEmployeeTraining(String recordId){
        try {
            return [
                SELECT 
                    Id, Name, Start_Date__c, End_Date__c, Status__c, Duration__c, Days_in_Training__c,
                    Ahead_Behind__c, Actual_Minutes__c, Achieved__c, Target_Minutes__c, Total_Minutes__c
                FROM 
                    Employee_Training__c 
                WHERE 
                    Id = :recordId
            ];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}