force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold information about activities that will be part of trainings and related to employees</description>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/Total_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Total_Minutes__c</fullName>
    <label>Total Minutes</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Activity__c/Employee_Activity__c.object-meta.xml
<CustomObject>
    <description>Custom object to relate activities with employees</description>
    <label>Employee Activity</label>
    <nameField>
        <label>Employee Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Activity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Employee Activities</relationshipLabel>
    <relationshipName>Employee_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Activity__c/fields/Employee_Training__c.field-meta.xml
<CustomField>
    <fullName>Employee_Training__c</fullName>
    <label>Employee Training</label>
    <referenceTo>Employee_Training__c</referenceTo>
    <relationshipLabel>Employee Activities</relationshipLabel>
    <relationshipName>Employee_Activities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Activity__c/fields/Total_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Total_Minutes__c</fullName>
    <description>Total minutes to complete this activity. Same total minutes from parent activity but needed to rollup to employee training</description>
    <label>Total Minutes</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/Employee_Training__c.object-meta.xml
<CustomObject>
    <description>Custom object to relate employees with trainings</description>
    <label>Employee Training</label>
    <nameField>
        <label>Employee Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>&quot;On Pace&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Total_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Total_Minutes__c</fullName>
    <description>Sum of total minutes from related employee activities</description>
    <label>Total Minutes</label>
    <summarizedField>Employee_Activity__c.Total_Minutes__c</summarizedField>
    <summaryForeignKey>Employee_Activity__c.Employee_Training__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Employee_Training__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Employee Trainings</relationshipLabel>
    <relationshipName>Employee_Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <description>Custom object to store information about trainings</description>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Total_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Total_Minutes__c</fullName>
    <description>Total minutes to complete this training</description>
    <label>Total Minutes</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training_Activity__c/Training_Activity__c.object-meta.xml
<CustomObject>
    <description>Custom object to relate activities with trainings</description>
    <label>Training Activity</label>
    <nameField>
        <displayFormat>TA-{00000}</displayFormat>
        <label>Training Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Activity__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Training Activities</relationshipLabel>
    <relationshipName>Training_Activities</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Activity__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Training Activities</relationshipLabel>
    <relationshipName>Training_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EmployeeTrainingTriggerHandler.cls
public inherited sharing class EmployeeTrainingTriggerHandler {

    private static final String EMPLOYEE_ACTTIVITY_DEFAULT_STATUS = 'To Do';

    /*
        When a new employee Contact is created, generate a set of Onboarding Activities for them.
    */
    public void CreateEmployeeActivities(List<Employee_Training__c> employeeTrainings) {

        // Gather the Ids of all Training__c records we will need
        // Use a set because multiple employeeTrainings might have same onboarding, but we only need to collect all unique Ids
        Set<ID> trainingIds = new Set<ID>();
        for (Employee_Training__c employeeTraining : employeeTrainings) {
            if (employeeTraining.Training__c != null)  {
                trainingIds.add(employeeTraining.Training__c);
            }
        }

        if (trainingIds.isEmpty()) {
            // None of the new employeeTrainings have an onboarding -- there's nothing further to do.
            return;
        }
        
        // Select all the Training__c records along with all their child Training_Activity__c records
        // Onboarding_Activities__r indicates a relationship where Training__c has related Training_Activity__c records
        // The map constructor will automatically map them by their ID
        Map<Id, Training__c> trainingMap = new Map<Id, Training__c>(
            [
                SELECT
                    Id,
                    (SELECT Id, Activity__c, Activity__r.Name, Activity__r.Total_Minutes__c FROM Training_Activities__r)
                FROM 
                    Training__c
                WHERE
                    Id IN :trainingIds
            ]
        );

        // Build out employeeActivities for each employeeTraining
        List<Employee_Activity__c> employeeActivities = new List<Employee_Activity__c>();
        for (Employee_Training__c employeeTraining : employeeTrainings) {
            if (employeeTraining.Training__c != null) {

                // Retrieve the training from the map
                Training__c training = trainingMap.get(employeeTraining.Training__c);

                // Add each assignment to list of new employeeActivities
                for (Training_Activity__c trainingActivity : training.Training_Activities__r) {
                    employeeActivities.add(
                        new Employee_Activity__c(
                            Name = trainingActivity.Activity__r.Name,
                            Activity__c = trainingActivity.Activity__c, 
                            Employee_Training__c = employeeTraining.Id,
                            Total_Minutes__c = trainingActivity.Activity__r.Total_Minutes__c,
                            Status__c = EMPLOYEE_ACTTIVITY_DEFAULT_STATUS));
                }
            }
        }

        // Insert the employeeActivities -- if there are any
        if (!employeeActivities.isEmpty()) {
            insert employeeActivities;
        }
    }

}